### ISSUE TITLE
Endpoint to update clio dataset information

### ISSUE THREAD

**Issue by stuarteberg** [clio-janelia/clio-store#8]
On Wednesday, @DocSavage said he would create an endpoint that makes it more convenient to update the clio dataset information for new UUIDs, etc.

**Comment by DocSavage** [comment]
This has been handled by commit 39672d.  We can create templated dataset objects that use `{tag}` and `{uuid}` strings within keys and values.  Those placeholders will be replaced with the values for the top-level `tag` and `uuid` fields in a dataset object.
